
[Interface]
PrivateKey = yaFDq8ODWSeb2+BPNWpk7EgFQ0C4Tx14UBKK5hSIGKE=
Address = fdaa:7e:680a:a7b:81c:15cd:7a4b:4202/120
DNS = fdaa:7e:680a::3

[Peer]
PublicKey = x4M328n2dyyQ8rA1JKJUXJR7hvCcPiH05IuaGLbmmAg=
AllowedIPs = fdaa:7e:680a::/48
Endpoint = gru1.gateway.6pn.dev:51820
PersistentKeepalive = 15

