# fly.toml app configuration file generated for bjjrats on 2026-06-18T01:07:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bjjrats'
primary_region = 'gru'

[build]
  [build.args]
    VITE_TURNSTILE_SITE_KEY = "0x4AAAAAADm4HnOK8P1JV2Ss"

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  UPLOADS_DIR = '/app/uploads'

[[mounts]]
  source = 'bjjrats_uploads'
  destination = '/app/uploads'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
