import 'dotenv/config';
import bcrypt from 'bcryptjs';
import { sql } from 'drizzle-orm';
import { db, pool } from './index.js';
import {
  academyProfessorLinks,
  academyRequests,
  academyStudentProfessorAssignments,
  announcementDismissals,
  announcements,
  challenges,
  classCheckIns,
  classSchedules,
  comments,
  competitions,
  enrollments,
  events,
  extraTrainings,
  goals,
  notifications,
  payments,
  plans,
  posts,
  promotions,
  settings,
  subscriptions,
  trainings,
  userAchievements,
  users,
  whatsappInstances,
} from './schema.js';

const CONFIRM_VALUE = 'reset-dev-data';
const PASSWORD = process.env.DEV_SEED_PASSWORD || 'Teste@123';

const ids = {
  superadmin: 'dev_superadmin',
  academy: 'dev_academy_matriz',
  professorInternal: 'dev_professor_interno',
  professorPartner: 'dev_professor_parceiro',
  professorPrivate: 'dev_professor_particular',
  studentActive: 'dev_aluno_ativo',
  studentSuspended: 'dev_aluna_suspensa',
  studentPartner: 'dev_aluno_parceiro',
  studentPrivate: 'dev_aluna_particular',
  studentVisitor: 'dev_visitante',
};

const appTables = [
  'announcement_dismissals',
  'announcements',
  'class_check_ins',
  'class_schedules',
  'academy_student_professor_assignments',
  'academy_professor_links',
  'academy_requests',
  'comments',
  'posts',
  'events',
  'challenges',
  'notifications',
  'payments',
  'promotions',
  'competitions',
  'user_achievements',
  'goals',
  'extra_trainings',
  'trainings',
  'enrollments',
  'subscriptions',
  'settings',
  'plans',
  'whatsapp_instances',
  'users',
];

function qident(name: string) {
  return `"${name.replace(/"/g, '""')}"`;
}

function addDays(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date;
}

function dateOnly(days: number) {
  return addDays(days).toISOString().slice(0, 10);
}

function assertSafeTarget() {
  if (process.env.BJJ_SEED_DEV_CONFIRM !== CONFIRM_VALUE) {
    throw new Error(`Defina BJJ_SEED_DEV_CONFIRM=${CONFIRM_VALUE} para rodar este seed.`);
  }

  const url = process.env.DATABASE_URL;
  if (!url) throw new Error('DATABASE_URL nao configurado.');

  const databaseName = new URL(url).pathname.replace(/^\//, '');
  const allowed = process.env.BJJ_SEED_ALLOW_NON_DEV === 'true';
  if (!allowed && !databaseName.toLowerCase().includes('dev')) {
    throw new Error(`Seed dev bloqueado para o banco "${databaseName}".`);
  }
}

async function resetDevData(tx: any) {
  const tableList = appTables.map((name) => `public.${qident(name)}`).join(', ');
  await tx.execute(sql.raw(`truncate table ${tableList} restart identity cascade`));
}

async function seedDev() {
  assertSafeTarget();

  const passwordHash = await bcrypt.hash(PASSWORD, 10);
  const now = new Date();

  const planRows = [
    {
      id: 'plan_student_dev',
      slug: 'aluno',
      name: 'Aluno',
      description: 'Registro de treinos, evolucao, comunidade e metas.',
      price: 19.9,
      roleAssigned: 'student',
      trialDays: 7,
      features: [
        'training_tracking',
        'training_history',
        'streak',
        'community',
        'achievements',
        'competitions',
        'goals',
        'challenges',
        'events',
        'profile_stats',
      ],
    },
    {
      id: 'plan_professor_dev',
      slug: 'professor',
      name: 'Professor Particular',
      description: 'Gestao de alunos, matriculas, mensalidades e turmas.',
      price: 47.9,
      roleAssigned: 'professor',
      trialDays: 7,
      features: [
        'professor_panel',
        'student_management',
        'unlimited_students',
        'enrollments',
        'payments',
        'promotions',
        'class_schedules',
        'class_checkins',
        'training_analytics',
      ],
    },
    {
      id: 'plan_academy_dev',
      slug: 'academia',
      name: 'Academia',
      description: 'CRM, gestao de alunos, professores, financeiro e relatorios.',
      price: 97.9,
      roleAssigned: 'academy',
      trialDays: 7,
      features: [
        'academy_dashboard',
        'crm',
        'multiple_professors',
        'class_schedules',
        'class_checkins',
        'reports',
        'enrollments',
        'payments',
        'promotions',
        'revenue_analytics',
      ],
    },
  ];

  const userRows = [
    {
      uid: ids.superadmin,
      name: 'Super Admin Dev',
      email: 'admin@bjjrats.dev',
      role: 'superadmin',
      belt: 'Preta',
      stripes: 4,
      passwordHash,
      subscriptionExempt: true,
      isAcademyAdmin: true,
      communityModerator: true,
      createdAt: now,
    },
    {
      uid: ids.academy,
      name: 'Academia Matriz BJJRats',
      email: 'academia@bjjrats.dev',
      role: 'academy',
      belt: 'Preta',
      stripes: 3,
      passwordHash,
      subscriptionExempt: false,
      isAcademyAdmin: true,
      communityModerator: true,
      phone: '11999990001',
      academy: 'Academia Matriz BJJRats',
      academyName: 'Academia Matriz BJJRats',
      academyAddress: 'Avenida Paulista, 1000',
      academyCep: '01310930',
      academyNumber: '1000',
      academyNeighborhood: 'Bela Vista',
      academyCity: 'Sao Paulo',
      academyState: 'SP',
      academyLatitude: -23.5617,
      academyLongitude: -46.6559,
      academyPhone: '11999990001',
      academyInstagram: 'bjjrats.dev',
      academyStyle: 'Gi e No-Gi',
      academyFranchise: 'BJJRats',
      academyMonthlyFee: 189.9,
      academyDailyFee: 35,
      academyPixKey: 'pix-academia@bjjrats.dev',
      academyLogoUrl: '/favicon.png',
      academyPhotoUrls: ['/favicon.png'],
      trialRequestsEnabled: true,
      promotionCriteria: [
        { belt: 'Azul', trainings: 120, months: 18 },
        { belt: 'Roxa', trainings: 260, months: 36 },
      ],
      createdAt: now,
    },
    {
      uid: ids.professorInternal,
      name: 'Mestre Bruno Interno',
      email: 'prof.interno@bjjrats.dev',
      role: 'professor',
      belt: 'Preta',
      stripes: 2,
      passwordHash,
      subscriptionExempt: false,
      academy: 'Academia Matriz BJJRats',
      academyId: ids.academy,
      professorPhotoUrl: '/favicon.png',
      phone: '11999990002',
      trialRequestsEnabled: false,
      createdAt: now,
    },
    {
      uid: ids.professorPartner,
      name: 'Mestre Caio Parceiro',
      email: 'prof.parceiro@bjjrats.dev',
      role: 'professor',
      belt: 'Preta',
      stripes: 1,
      passwordHash,
      subscriptionExempt: false,
      professorPhotoUrl: '/favicon.png',
      phone: '11999990003',
      academyName: 'Nucleo Parceiro Caio',
      academyAddress: 'Rua Augusta, 1500',
      academyCep: '01305000',
      academyCity: 'Sao Paulo',
      academyState: 'SP',
      academyLatitude: -23.5567,
      academyLongitude: -46.6624,
      trialRequestsEnabled: true,
      createdAt: now,
    },
    {
      uid: ids.professorPrivate,
      name: 'Mestre Diego Particular',
      email: 'prof.particular@bjjrats.dev',
      role: 'professor',
      belt: 'Preta',
      stripes: 2,
      passwordHash,
      subscriptionExempt: false,
      professorPhotoUrl: '/favicon.png',
      phone: '11999990004',
      academyName: 'Atendimento Particular Diego',
      academyAddress: 'Rua Vergueiro, 900',
      academyCep: '01504001',
      academyCity: 'Sao Paulo',
      academyState: 'SP',
      academyLatitude: -23.5731,
      academyLongitude: -46.6394,
      academyMonthlyFee: 249.9,
      academyPixKey: 'pix-professor@bjjrats.dev',
      trialRequestsEnabled: true,
      createdAt: now,
    },
    {
      uid: ids.studentActive,
      name: 'Ana Aluna Ativa',
      email: 'aluno@bjjrats.dev',
      role: 'student',
      belt: 'Branca',
      stripes: 2,
      passwordHash,
      phone: '11999990101',
      academy: 'Academia Matriz BJJRats',
      academyId: ids.academy,
      professor: 'Mestre Bruno Interno',
      xp: 1840,
      totalTrainings: 42,
      totalMinutes: 3150,
      streak: 5,
      lastTrainingDate: dateOnly(-1),
      athleteType: 'competidor',
      createdAt: now,
    },
    {
      uid: ids.studentSuspended,
      name: 'Bia Aluna Suspensa',
      email: 'aluna.suspensa@bjjrats.dev',
      role: 'student',
      belt: 'Azul',
      stripes: 1,
      passwordHash,
      phone: '11999990102',
      academy: 'Academia Matriz BJJRats',
      academyId: ids.academy,
      professor: 'Mestre Bruno Interno',
      xp: 3240,
      totalTrainings: 88,
      totalMinutes: 6600,
      streak: 0,
      lastTrainingDate: dateOnly(-18),
      athleteType: 'hobby',
      createdAt: now,
    },
    {
      uid: ids.studentPartner,
      name: 'Carlos Aluno Parceiro',
      email: 'aluno.parceiro@bjjrats.dev',
      role: 'student',
      belt: 'Branca',
      stripes: 3,
      passwordHash,
      phone: '11999990103',
      academy: 'Academia Matriz BJJRats',
      academyId: ids.academy,
      professor: 'Mestre Caio Parceiro',
      xp: 990,
      totalTrainings: 24,
      totalMinutes: 1780,
      streak: 2,
      lastTrainingDate: dateOnly(-2),
      athleteType: 'hobby',
      createdAt: now,
    },
    {
      uid: ids.studentPrivate,
      name: 'Duda Aluna Particular',
      email: 'aluna.particular@bjjrats.dev',
      role: 'student',
      belt: 'Branca',
      stripes: 1,
      passwordHash,
      phone: '11999990104',
      academy: 'Atendimento Particular Diego',
      professor: 'Mestre Diego Particular',
      xp: 620,
      totalTrainings: 14,
      totalMinutes: 1020,
      streak: 1,
      lastTrainingDate: dateOnly(-3),
      athleteType: 'iniciante',
      createdAt: now,
    },
    {
      uid: ids.studentVisitor,
      name: 'Eva Visitante',
      email: 'visitante@bjjrats.dev',
      role: 'student',
      belt: 'Branca',
      stripes: 0,
      passwordHash,
      phone: '11999990105',
      xp: 120,
      totalTrainings: 3,
      totalMinutes: 210,
      streak: 0,
      athleteType: 'iniciante',
      savedAcademies: [ids.academy],
      savedProfessors: [ids.professorPrivate],
      createdAt: now,
    },
  ];

  await db.transaction(async (tx) => {
    await resetDevData(tx);

    await tx.insert(plans).values(planRows as any);
    await tx.insert(users).values(userRows as any);

    await tx.insert(subscriptions).values([
      {
        id: 'sub_academy_dev',
        userUid: ids.academy,
        planId: 'plan_academy_dev',
        status: 'active',
        currentPeriodStart: addDays(-15),
        currentPeriodEnd: addDays(15),
        createdAt: addDays(-15),
      },
      {
        id: 'sub_partner_dev',
        userUid: ids.professorPartner,
        planId: 'plan_professor_dev',
        status: 'active',
        currentPeriodStart: addDays(-12),
        currentPeriodEnd: addDays(18),
        createdAt: addDays(-12),
      },
      {
        id: 'sub_private_dev',
        userUid: ids.professorPrivate,
        planId: 'plan_professor_dev',
        status: 'active',
        currentPeriodStart: addDays(-12),
        currentPeriodEnd: addDays(18),
        createdAt: addDays(-12),
      },
      ...[ids.studentActive, ids.studentSuspended, ids.studentPartner, ids.studentPrivate, ids.studentVisitor].map((uid, index) => ({
        id: `sub_student_${index + 1}_dev`,
        userUid: uid,
        planId: 'plan_student_dev',
        status: 'active',
        currentPeriodStart: addDays(-8),
        currentPeriodEnd: addDays(22),
        createdAt: addDays(-8),
      })),
    ] as any);

    await tx.insert(settings).values([
      { key: 'play_store_url', value: 'https://example.com/bjjrats-android-dev' },
      { key: 'app_store_url', value: 'https://example.com/bjjrats-ios-dev' },
      { key: `professor:${ids.academy}:financial:auto_suspend_after_days`, value: '15' },
      { key: `professor:${ids.professorPrivate}:financial:auto_suspend_after_days`, value: '10' },
      { key: `owner:${ids.academy}:payments:manual_enabled`, value: 'true' },
      { key: `owner:${ids.academy}:payments:asaas_enabled`, value: 'false' },
      { key: `owner:${ids.academy}:payments:asaas_sandbox`, value: 'true' },
      { key: `owner:${ids.academy}:payments:asaas_billing_type`, value: 'PIX' },
      { key: `owner:${ids.academy}:payments:pix_key`, value: 'pix-academia@bjjrats.dev' },
      { key: `owner:${ids.academy}:payments:webhook_token`, value: 'dev-webhook-academia' },
      { key: `owner:${ids.professorPrivate}:payments:manual_enabled`, value: 'true' },
      { key: `owner:${ids.professorPrivate}:payments:asaas_enabled`, value: 'false' },
      { key: `owner:${ids.professorPrivate}:payments:asaas_sandbox`, value: 'true' },
      { key: `owner:${ids.professorPrivate}:payments:asaas_billing_type`, value: 'PIX' },
      { key: `owner:${ids.professorPrivate}:payments:pix_key`, value: 'pix-professor@bjjrats.dev' },
      { key: `owner:${ids.professorPrivate}:payments:webhook_token`, value: 'dev-webhook-professor' },
    ]);

    await tx.insert(academyProfessorLinks).values([
      {
        id: 'link_internal_dev',
        academyUid: ids.academy,
        professorUid: ids.professorInternal,
        relationType: 'internal',
        status: 'active',
        notes: 'Professor contratado pela academia.',
        createdByUid: ids.academy,
        createdAt: addDays(-20),
        updatedAt: addDays(-20),
      },
      {
        id: 'link_partner_dev',
        academyUid: ids.academy,
        professorUid: ids.professorPartner,
        relationType: 'partner',
        status: 'active',
        partnerRevenueSharePercent: 45,
        partnerRevenueNotes: 'Divisao de 45% para o professor parceiro.',
        notes: 'Professor parceiro aceito.',
        createdByUid: ids.academy,
        createdAt: addDays(-12),
        updatedAt: addDays(-10),
      },
      {
        id: 'link_pending_private_dev',
        academyUid: ids.academy,
        professorUid: ids.professorPrivate,
        relationType: 'partner',
        status: 'pending',
        partnerRevenueSharePercent: 50,
        partnerRevenueNotes: 'Convite pendente para parceria.',
        createdByUid: ids.academy,
        createdAt: addDays(-1),
        updatedAt: addDays(-1),
      },
    ] as any);

    await tx.insert(enrollments).values([
      {
        id: 'enr_academy_active_dev',
        professorUid: ids.academy,
        professorName: 'Academia Matriz BJJRats',
        academyName: 'Academia Matriz BJJRats',
        studentUid: ids.studentActive,
        studentName: 'Ana Aluna Ativa',
        monthlyFee: 189.9,
        dueDay: 10,
        status: 'active',
        pixKey: 'pix-academia@bjjrats.dev',
        createdAt: addDays(-45),
      },
      {
        id: 'enr_academy_suspended_dev',
        professorUid: ids.academy,
        professorName: 'Academia Matriz BJJRats',
        academyName: 'Academia Matriz BJJRats',
        studentUid: ids.studentSuspended,
        studentName: 'Bia Aluna Suspensa',
        monthlyFee: 189.9,
        dueDay: 5,
        status: 'suspended',
        pixKey: 'pix-academia@bjjrats.dev',
        createdAt: addDays(-80),
      },
      {
        id: 'enr_academy_partner_dev',
        professorUid: ids.academy,
        professorName: 'Academia Matriz BJJRats',
        academyName: 'Academia Matriz BJJRats',
        studentUid: ids.studentPartner,
        studentName: 'Carlos Aluno Parceiro',
        monthlyFee: 209.9,
        dueDay: 12,
        status: 'active',
        pixKey: 'pix-academia@bjjrats.dev',
        createdAt: addDays(-25),
      },
      {
        id: 'enr_private_active_dev',
        professorUid: ids.professorPrivate,
        professorName: 'Mestre Diego Particular',
        academyName: 'Atendimento Particular Diego',
        studentUid: ids.studentPrivate,
        studentName: 'Duda Aluna Particular',
        monthlyFee: 249.9,
        dueDay: 15,
        status: 'active',
        pixKey: 'pix-professor@bjjrats.dev',
        createdAt: addDays(-35),
      },
    ] as any);

    await tx.insert(academyStudentProfessorAssignments).values([
      {
        id: 'assign_internal_active_dev',
        academyUid: ids.academy,
        professorUid: ids.professorInternal,
        studentUid: ids.studentActive,
        relationType: 'internal',
        status: 'active',
        studentName: 'Ana Aluna Ativa',
        professorName: 'Mestre Bruno Interno',
        notes: 'Aluno distribuido pela academia.',
        createdByUid: ids.academy,
        createdAt: addDays(-30),
        updatedAt: addDays(-30),
      },
      {
        id: 'assign_partner_active_dev',
        academyUid: ids.academy,
        professorUid: ids.professorPartner,
        studentUid: ids.studentPartner,
        relationType: 'partner',
        status: 'accepted',
        studentName: 'Carlos Aluno Parceiro',
        professorName: 'Mestre Caio Parceiro',
        notes: 'Aluno enviado para professor parceiro.',
        createdByUid: ids.academy,
        decidedAt: addDays(-5),
        createdAt: addDays(-8),
        updatedAt: addDays(-5),
      },
      {
        id: 'assign_partner_pending_dev',
        academyUid: ids.academy,
        professorUid: ids.professorPartner,
        studentUid: ids.studentVisitor,
        relationType: 'partner',
        status: 'pending',
        studentName: 'Eva Visitante',
        professorName: 'Mestre Caio Parceiro',
        notes: 'Indicacao aguardando aceite do professor parceiro.',
        createdByUid: ids.academy,
        createdAt: addDays(-1),
        updatedAt: addDays(-1),
      },
    ] as any);

    await tx.insert(academyRequests).values([
      {
        id: 'req_pending_visitor_dev',
        studentUid: ids.studentVisitor,
        studentName: 'Eva Visitante',
        studentEmail: 'visitante@bjjrats.dev',
        studentBelt: 'Branca',
        professorUid: ids.academy,
        academyName: 'Academia Matriz BJJRats',
        status: 'pending',
        createdAt: addDays(-1),
      },
      {
        id: 'req_accepted_active_dev',
        studentUid: ids.studentActive,
        studentName: 'Ana Aluna Ativa',
        studentEmail: 'aluno@bjjrats.dev',
        studentBelt: 'Branca',
        professorUid: ids.academy,
        academyName: 'Academia Matriz BJJRats',
        status: 'accepted',
        createdAt: addDays(-40),
      },
    ] as any);

    await tx.insert(classSchedules).values([
      {
        id: 'schedule_fundamentos_dev',
        academyId: ids.academy,
        professorUid: ids.professorInternal,
        dayOfWeek: 1,
        startTime: '19:00',
        endTime: '20:30',
        className: 'Fundamentos',
        modality: 'BJJ',
        days: ['seg', 'qua'],
        time: '19:00',
        type: 'Fundamentos',
        mode: 'Presencial',
        publico: 'Iniciantes',
        durationMin: 90,
        notes: 'Turma inicial da academia.',
        createdAt: addDays(-20),
      },
      {
        id: 'schedule_avancado_dev',
        academyId: ids.academy,
        professorUid: ids.professorPartner,
        dayOfWeek: 2,
        startTime: '20:30',
        endTime: '22:00',
        className: 'Treino avancado',
        modality: 'BJJ',
        days: ['ter', 'qui'],
        time: '20:30',
        type: 'Avancado',
        mode: 'Presencial',
        publico: 'Graduados',
        durationMin: 90,
        notes: 'Turma com professor parceiro.',
        createdAt: addDays(-16),
      },
      {
        id: 'schedule_private_dev',
        academyId: ids.professorPrivate,
        professorUid: ids.professorPrivate,
        dayOfWeek: 6,
        startTime: '09:00',
        endTime: '10:30',
        className: 'Aula particular',
        modality: 'BJJ',
        days: ['sab'],
        time: '09:00',
        type: 'Particular',
        mode: 'Presencial',
        publico: 'Alunos particulares',
        durationMin: 90,
        notes: 'Horario individual.',
        createdAt: addDays(-12),
      },
    ] as any);

    await tx.insert(classCheckIns).values([
      { id: 'check_ana_1_dev', scheduleId: 'schedule_fundamentos_dev', academyId: ids.academy, studentUid: ids.studentActive, checkInDate: dateOnly(-1), createdAt: addDays(-1) },
      { id: 'check_ana_2_dev', scheduleId: 'schedule_fundamentos_dev', academyId: ids.academy, studentUid: ids.studentActive, checkInDate: dateOnly(-3), createdAt: addDays(-3) },
      { id: 'check_carlos_1_dev', scheduleId: 'schedule_avancado_dev', academyId: ids.academy, studentUid: ids.studentPartner, checkInDate: dateOnly(-2), createdAt: addDays(-2) },
      { id: 'check_duda_1_dev', scheduleId: 'schedule_private_dev', academyId: ids.professorPrivate, studentUid: ids.studentPrivate, checkInDate: dateOnly(-3), createdAt: addDays(-3) },
    ] as any);

    await tx.insert(payments).values([
      {
        id: 'pay_ana_paid_dev',
        professorUid: ids.academy,
        studentUid: ids.studentActive,
        studentName: 'Ana Aluna Ativa',
        studentEmail: 'aluno@bjjrats.dev',
        amount: 189.9,
        dueDate: addDays(-20),
        paidAt: addDays(-18),
        status: 'paid',
        pixLink: 'pix-academia@bjjrats.dev',
        createdAt: addDays(-25),
      },
      {
        id: 'pay_ana_pending_dev',
        professorUid: ids.academy,
        studentUid: ids.studentActive,
        studentName: 'Ana Aluna Ativa',
        studentEmail: 'aluno@bjjrats.dev',
        amount: 189.9,
        dueDate: addDays(5),
        status: 'pending',
        pixLink: 'pix-academia@bjjrats.dev',
        createdAt: addDays(-2),
      },
      {
        id: 'pay_bia_overdue_dev',
        professorUid: ids.academy,
        studentUid: ids.studentSuspended,
        studentName: 'Bia Aluna Suspensa',
        studentEmail: 'aluna.suspensa@bjjrats.dev',
        amount: 189.9,
        dueDate: addDays(-22),
        status: 'overdue',
        pixLink: 'pix-academia@bjjrats.dev',
        createdAt: addDays(-25),
      },
      {
        id: 'pay_carlos_paid_dev',
        professorUid: ids.academy,
        studentUid: ids.studentPartner,
        studentName: 'Carlos Aluno Parceiro',
        studentEmail: 'aluno.parceiro@bjjrats.dev',
        amount: 209.9,
        dueDate: addDays(-8),
        paidAt: addDays(-6),
        status: 'paid',
        pixLink: 'pix-academia@bjjrats.dev',
        createdAt: addDays(-12),
      },
      {
        id: 'pay_duda_paid_dev',
        professorUid: ids.professorPrivate,
        studentUid: ids.studentPrivate,
        studentName: 'Duda Aluna Particular',
        studentEmail: 'aluna.particular@bjjrats.dev',
        amount: 249.9,
        dueDate: addDays(-12),
        paidAt: addDays(-12),
        status: 'paid',
        pixLink: 'pix-professor@bjjrats.dev',
        createdAt: addDays(-15),
      },
      {
        id: 'pay_duda_pending_dev',
        professorUid: ids.professorPrivate,
        studentUid: ids.studentPrivate,
        studentName: 'Duda Aluna Particular',
        studentEmail: 'aluna.particular@bjjrats.dev',
        amount: 249.9,
        dueDate: addDays(3),
        status: 'pending',
        pixLink: 'pix-professor@bjjrats.dev',
        createdAt: addDays(-1),
      },
    ] as any);

    await tx.insert(trainings).values([
      {
        id: 'train_ana_1_dev',
        uid: ids.studentActive,
        trainingDate: dateOnly(-1),
        sessionType: 'Aula',
        modality: 'BJJ',
        duration: 90,
        intensity: 4,
        satisfaction: 5,
        techniques: { guarda: ['passagem torreando'], finalizacao: ['arm lock'] },
        notes: 'Treino de fundamentos com passagem de guarda.',
        academy: 'Academia Matriz BJJRats',
        professor: 'Mestre Bruno Interno',
        xp: 60,
        createdAt: addDays(-1),
      },
      {
        id: 'train_carlos_1_dev',
        uid: ids.studentPartner,
        trainingDate: dateOnly(-2),
        sessionType: 'Sparring',
        modality: 'BJJ',
        duration: 90,
        intensity: 5,
        satisfaction: 4,
        techniques: { raspagem: ['gancho'], queda: ['single leg'] },
        notes: 'Rodadas intensas com turma avancada.',
        academy: 'Academia Matriz BJJRats',
        professor: 'Mestre Caio Parceiro',
        xp: 80,
        createdAt: addDays(-2),
      },
      {
        id: 'train_duda_1_dev',
        uid: ids.studentPrivate,
        trainingDate: dateOnly(-3),
        sessionType: 'Particular',
        modality: 'BJJ',
        duration: 75,
        intensity: 3,
        satisfaction: 5,
        techniques: { defesa: ['saida da montada'] },
        notes: 'Ajustes basicos de defesa.',
        academy: 'Atendimento Particular Diego',
        professor: 'Mestre Diego Particular',
        xp: 50,
        createdAt: addDays(-3),
      },
    ] as any);

    await tx.insert(extraTrainings).values([
      { id: 'extra_ana_mobility_dev', uid: ids.studentActive, trainingDate: dateOnly(-4), activity: 'Mobilidade', duration: 30, notes: 'Mobilidade de quadril.', createdAt: addDays(-4) },
    ] as any);

    await tx.insert(goals).values([
      { id: 'goal_ana_week_dev', uid: ids.studentActive, title: 'Treinar 4 vezes na semana', target: 4, unit: 'treinos', period: 'weekly', isActive: true, createdAt: addDays(-7) },
      { id: 'goal_duda_month_dev', uid: ids.studentPrivate, title: 'Completar 12 aulas no mes', target: 12, unit: 'aulas', period: 'monthly', isActive: true, createdAt: addDays(-10) },
    ] as any);

    await tx.insert(posts).values([
      {
        id: 'post_academy_news_dev',
        authorUid: ids.academy,
        authorName: 'Academia Matriz BJJRats',
        authorPhoto: '/favicon.png',
        authorBelt: 'Preta',
        content: 'Semana de ajustes de guarda aberta na matriz. Tragam kimono revisado e cheguem 10 minutos antes.',
        postType: 'academy',
        academyId: ids.academy,
        academyName: 'Academia Matriz BJJRats',
        academyLogo: '/favicon.png',
        likes: [ids.studentActive, ids.studentPartner],
        createdAt: addDays(-2),
      },
      {
        id: 'post_ana_training_dev',
        authorUid: ids.studentActive,
        authorName: 'Ana Aluna Ativa',
        authorBelt: 'Branca',
        content: 'Hoje a passagem de guarda finalmente encaixou. OSS!',
        postType: 'training',
        academyId: ids.academy,
        academyName: 'Academia Matriz BJJRats',
        trainingData: { duration: 90, xp: 60, professor: 'Mestre Bruno Interno' },
        likes: [ids.professorInternal],
        createdAt: addDays(-1),
      },
      {
        id: 'post_prof_private_dev',
        authorUid: ids.professorPrivate,
        authorName: 'Mestre Diego Particular',
        authorPhoto: '/favicon.png',
        authorBelt: 'Preta',
        content: 'Horarios particulares de sabado atualizados para iniciantes.',
        postType: 'community',
        likes: [ids.studentPrivate],
        createdAt: addDays(-3),
      },
    ] as any);

    await tx.insert(comments).values([
      { id: 'comment_post_ana_dev', postId: 'post_ana_training_dev', authorUid: ids.professorInternal, authorName: 'Mestre Bruno Interno', authorPhoto: '/favicon.png', content: 'Boa evolucao. Continua nesse ritmo.', createdAt: addDays(-1) },
    ] as any);

    await tx.insert(events).values([
      {
        id: 'event_open_mat_dev',
        creatorUid: ids.academy,
        academyId: ids.academy,
        title: 'Open Mat de Sabado',
        description: 'Treino livre para alunos e convidados.',
        type: 'open-mat',
        eventDate: dateOnly(6),
        eventTime: '10:00',
        location: 'Academia Matriz BJJRats',
        slots: 40,
        price: 'Gratuito para alunos',
        duration: '2h',
        academyName: 'Academia Matriz BJJRats',
        academyLogo: '/favicon.png',
        locationCep: '01310930',
        locationAddress: 'Avenida Paulista',
        locationNumber: '1000',
        locationNeighborhood: 'Bela Vista',
        locationCity: 'Sao Paulo',
        locationState: 'SP',
        locationLatitude: -23.5617,
        locationLongitude: -46.6559,
        isPublic: true,
        rsvps: [ids.studentActive, ids.studentPartner],
        registrationNames: { [ids.studentActive]: 'Ana Aluna Ativa', [ids.studentPartner]: 'Carlos Aluno Parceiro' },
        registrationBelts: { [ids.studentActive]: 'Branca', [ids.studentPartner]: 'Branca' },
        createdAt: addDays(-4),
      },
      {
        id: 'event_private_trial_dev',
        creatorUid: ids.professorPrivate,
        title: 'Aula experimental particular',
        description: 'Aula introdutoria para novos alunos.',
        type: 'trial',
        eventDate: dateOnly(9),
        eventTime: '09:00',
        location: 'Rua Vergueiro, 900',
        slots: 6,
        price: 'Gratis',
        duration: '1h',
        academyName: 'Atendimento Particular Diego',
        locationCep: '01504001',
        locationAddress: 'Rua Vergueiro',
        locationNumber: '900',
        locationNeighborhood: 'Liberdade',
        locationCity: 'Sao Paulo',
        locationState: 'SP',
        locationLatitude: -23.5731,
        locationLongitude: -46.6394,
        isPublic: true,
        rsvps: [ids.studentVisitor],
        createdAt: addDays(-2),
      },
    ] as any);

    await tx.insert(challenges).values([
      {
        id: 'challenge_10_trainings_dev',
        creatorUid: ids.academy,
        academyId: ids.academy,
        title: 'Desafio 10 treinos',
        description: 'Complete 10 treinos no mes.',
        target: 10,
        unit: 'treinos',
        startDate: dateOnly(-5),
        endDate: dateOnly(25),
        isPublic: true,
        participants: [
          { uid: ids.studentActive, progress: 4 },
          { uid: ids.studentPartner, progress: 2 },
        ],
        createdAt: addDays(-5),
      },
      {
        id: 'challenge_private_mobility_dev',
        creatorUid: ids.professorPrivate,
        title: 'Mobilidade 7 dias',
        description: 'Rotina curta de mobilidade para iniciantes.',
        target: 7,
        unit: 'dias',
        startDate: dateOnly(-1),
        endDate: dateOnly(6),
        isPublic: true,
        participants: [{ uid: ids.studentPrivate, progress: 1 }],
        createdAt: addDays(-1),
      },
    ] as any);

    await tx.insert(promotions).values([
      {
        id: 'promo_ana_stripe_dev',
        professorUid: ids.academy,
        studentUid: ids.studentActive,
        studentName: 'Ana Aluna Ativa',
        fromBelt: 'Branca',
        toBelt: 'Branca',
        fromStripes: 1,
        toStripes: 2,
        notes: 'Bom volume de treinos e evolucao tecnica.',
        promotedAt: addDays(-10),
        createdAt: addDays(-10),
      },
      {
        id: 'promo_duda_stripe_dev',
        professorUid: ids.professorPrivate,
        studentUid: ids.studentPrivate,
        studentName: 'Duda Aluna Particular',
        fromBelt: 'Branca',
        toBelt: 'Branca',
        fromStripes: 0,
        toStripes: 1,
        notes: 'Primeiro ciclo concluido.',
        promotedAt: addDays(-6),
        createdAt: addDays(-6),
      },
    ] as any);

    await tx.insert(competitions).values([
      {
        id: 'comp_ana_dev',
        uid: ids.studentActive,
        name: 'Copa Dev BJJRats',
        date: dateOnly(-30),
        location: 'Sao Paulo - SP',
        category: 'Adulto',
        weightClass: 'Leve',
        result: 'silver',
        notes: 'Primeira competicao cadastrada para teste.',
        createdAt: addDays(-30),
      },
    ] as any);

    await tx.insert(userAchievements).values([
      { id: 'ach_ana_first_week_dev', uid: ids.studentActive, achievementId: 'first_week_complete', unlockedAt: addDays(-12) },
      { id: 'ach_carlos_streak_dev', uid: ids.studentPartner, achievementId: 'streak_2', unlockedAt: addDays(-2) },
    ] as any);

    await tx.insert(notifications).values([
      {
        id: 'notif_ana_payment_dev',
        toUid: ids.studentActive,
        fromUid: ids.academy,
        fromName: 'Academia Matriz BJJRats',
        type: 'payment',
        message: 'Sua proxima mensalidade vence em alguns dias. Mantenha tudo em dia para seguir treinando.',
        data: { paymentId: 'pay_ana_pending_dev', amount: 189.9 },
        read: false,
        createdAt: addDays(-1),
      },
      {
        id: 'notif_bia_suspended_dev',
        toUid: ids.studentSuspended,
        fromUid: ids.academy,
        fromName: 'Academia Matriz BJJRats',
        type: 'payment_suspended',
        message: 'Sua matricula esta suspensa por mensalidade em atraso. Regularize para voltar ao tatame.',
        data: { enrollmentId: 'enr_academy_suspended_dev', paymentId: 'pay_bia_overdue_dev', daysOverdue: 22 },
        read: false,
        createdAt: addDays(-1),
      },
      {
        id: 'notif_partner_invite_dev',
        toUid: ids.professorPrivate,
        fromUid: ids.academy,
        fromName: 'Academia Matriz BJJRats',
        type: 'academy_professor_partner',
        message: 'A academia convidou voce para uma parceria com divisao de 50% da mensalidade.',
        data: { linkId: 'link_pending_private_dev', partnerRevenueSharePercent: 50 },
        read: false,
        createdAt: addDays(-1),
      },
      {
        id: 'notif_assignment_partner_dev',
        toUid: ids.professorPartner,
        fromUid: ids.academy,
        fromName: 'Academia Matriz BJJRats',
        type: 'academy_student_assignment',
        message: 'Novo aluno indicado pela academia aguardando sua decisao.',
        data: { assignmentId: 'assign_partner_pending_dev', studentName: 'Eva Visitante' },
        read: false,
        createdAt: addDays(-1),
      },
      {
        id: 'notif_duda_due_dev',
        toUid: ids.studentPrivate,
        fromUid: ids.professorPrivate,
        fromName: 'Mestre Diego Particular',
        type: 'payment',
        message: 'Sua mensalidade particular vence em breve.',
        data: { paymentId: 'pay_duda_pending_dev', amount: 249.9 },
        read: false,
        createdAt: addDays(-1),
      },
    ] as any);

    await tx.insert(announcements).values([
      {
        id: 'ann_global_dev',
        title: 'Ambiente dev BJJRats',
        content: 'Este banco contem apenas dados ficticios para desenvolvimento e testes.',
        sourceUid: ids.superadmin,
        sourceName: 'Super Admin Dev',
        sourceRole: 'superadmin',
        scope: 'global',
        audience: 'all',
        urgent: true,
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'ann_academy_dev',
        title: 'Aviso da academia',
        content: 'Open mat confirmado para sabado as 10h.',
        sourceUid: ids.academy,
        sourceName: 'Academia Matriz BJJRats',
        sourceRole: 'academy',
        scope: 'academy',
        audience: 'students',
        targetAcademyId: ids.academy,
        urgent: false,
        isActive: true,
        createdAt: addDays(-1),
        updatedAt: addDays(-1),
      },
    ] as any);

    await tx.insert(announcementDismissals).values([
      {
        id: 'ann_dismiss_visitor_dev',
        announcementId: 'ann_global_dev',
        userUid: ids.studentVisitor,
        dismissedAt: addDays(-1),
      },
    ] as any);

    await tx.insert(whatsappInstances).values([
      {
        id: 'wa_academy_dev',
        professorUid: ids.academy,
        instanceName: 'bjjrats-dev-academia',
        status: 'disconnected',
        phone: '11999990001',
        createdAt: addDays(-2),
        updatedAt: addDays(-1),
      },
      {
        id: 'wa_private_dev',
        professorUid: ids.professorPrivate,
        instanceName: 'bjjrats-dev-professor',
        status: 'disconnected',
        phone: '11999990004',
        createdAt: addDays(-2),
        updatedAt: addDays(-1),
      },
    ] as any);
  });

  console.log('Seed dev concluido.');
  console.log(`Senha padrao das contas: ${PASSWORD}`);
  console.log('Contas:');
  console.log('  admin@bjjrats.dev');
  console.log('  academia@bjjrats.dev');
  console.log('  prof.interno@bjjrats.dev');
  console.log('  prof.parceiro@bjjrats.dev');
  console.log('  prof.particular@bjjrats.dev');
  console.log('  aluno@bjjrats.dev');
  console.log('  aluna.suspensa@bjjrats.dev');
  console.log('  aluno.parceiro@bjjrats.dev');
  console.log('  aluna.particular@bjjrats.dev');
  console.log('  visitante@bjjrats.dev');
}

seedDev()
  .catch((error) => {
    console.error('Erro no seed dev:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await pool.end();
  });
